### ISSUE TITLE
Placeholder for me.jpg

### ISSUE THREAD

**Issue by digitalcraftsman** [TiTi/hurock#3]
Would it be possible to add some sort of placeholder for the picture of the blog's owner in the sidebar? You're [linking](https://github.com/TiTi/hurock/blob/9eff348d1957ea3ff89cdf2529082fd0891937b1/layouts/partials/sidebar.html#L5) to `media/me.jpg`, but the file isn't in your repo. 

Since a demo will be generated for the theme gallery of Hugo themes, it just looks better to see a placeholder instead of the a fallback by browsers in the demo.

**Comment by TiTi** [comment]
Hello,
Yeah sure.
What is the recommendation here?
- Add a `media/me.jpg` image in the sources?
- Create a dedicated partial layout?
- Use a variable and include `<img />` only when specified?
- ...

I'm curious how it's done with other themes.

**Comment by digitalcraftsman** [comment]
I think the easiest way is to save the placeholder under `static/media/me.jpg`. Including a theme variable that makes the picture optional could be added if you wish.

> I'm curious how it's done with other themes.

This issue shouldn't be a big deal. I do it the same way in one of my (upcoming) [themes](https://github.com/digitalcraftsman/hugo-cactus-theme/blob/master/static/images/avatar.png).

**Comment by TiTi** [comment]
Done :)
