### ISSUE TITLE
Large images destroy the layout

### ISSUE THREAD

**Issue by protux** [TiTi/hurock#5]
Hi,
I wanted to add a large image as title image of a blog post (a bit like in the ananke theme) but the image is not scaled down to fit the content area. Instead, it stretches the whole content area and even gets the view area to be scrolled horizontally.

How to reproduce: just add a large image to a blogpost. e.g. 
`![Galaxy](https://wonderfulengineering.com/wp-content/uploads/2014/06/galaxy-wallpapers.jpeg "Test broken layout")`

Expected behaviour: no overflow, no hidden text behind the left bar.

Thanks for the nice theme btw.

**Comment by TiTi** [comment]
Hello,

I'm not a huge fan of client side image resizing.
According to the browser, the interpolation algorithm is not the same thus image might look different.
It's up to the author to reference a smaller image.

However, there is a workaround: you can't specify a height or width in markdown, but you can simply write html like that:

`<img src="https://wonderfulengineering.com/wp-content/uploads/2014/06/galaxy-wallpapers.jpeg" alt="Galaxy" width="600" />`
